### ISSUE TITLE
Possibility to configure the helm chart to provide DNS configuration for the pods

### ISSUE THREAD

**Issue by muhittink** [iris-connect/iris-gateway#203]
In some cases, the pods in a cluster needs another DNS configuration than the default one.
@jekutzsche could you tell me which services needs to resolve internet ip adresses so I can start a pull-request?
/cc @pascalrimann

**Comment by jekutzsche** [comment]
@muhittink 

Der Backend Service (in den Helm-Charts dürfte er noch Location Service heißen) benötigt auf die folgenden Domains Zugriff:

* `*.slack.com`
* `support.iris-gateway.de` (oder gleich `*.iris-gateway.de`)
* `*.github.com`

Die Services dürften die folgenden sein:
* Test = `ls-1`
* Prod = `locations-production-1`

**Comment by muhittink** [comment]
@jekutzsche OK, Danke. Die EPS brauchen das nicht? Nur der Backend?

**Comment by jekutzsche** [comment]
Korrekt!

**Comment by muhittink** [comment]
OK, hab das mal im PR eingetragen. Config fehlt in den Values noch aber das trage ich auch noch ein wenn wir soweit sind.

**Comment by muhittink** [comment]
PR deprecated. DNS Konfiguration nicht nötig da der Proxy auflöst. Idee ist nun eine Configmap zu deployen die die container als environment setzen.
