### ISSUE TITLE
RandomStringUtils ggf. austauschen

### ISSUE THREAD

**Issue by adewes** [iris-connect/iris-gateway#78]
Mir ist beim Durchlesen des Codes aufgefallen, dass `RandomStringUtils` genutzt wird, das sollte ggf. durch einen sicheren Zufallszahlengenerator ausgetauscht werden, da die Funktionen nicht kryptographisch sicher sind (https://commons.apache.org/proper/commons-lang/javadocs/api-3.9/org/apache/commons/lang3/RandomStringUtils.html). Wird allerdings nur in zwei Stellen verwendet soweit ich das sehe:

https://github.com/iris-gateway/IRIS/blob/498199e994b35ca8817e3cae3a752104aa4bf3c8/iris-client-sormas-sidecar/src/main/java/de/healthIMIS/iris/client/core/IrisClientProperties.java
https://github.com/iris-gateway/IRIS/blob/498199e994b35ca8817e3cae3a752104aa4bf3c8/iris-client-sormas-sidecar/src/main/java/de/healthIMIS/iris/client/data_request/DataRequestManagement.java

**Comment by jekutzsche** [comment]
`RandomStringUtils` wird nicht mehr verwendet.
